# Numpy Package

1. Numerical data
2. Computations 

In [7]:
import numpy as np

### Difference between numpy array and list:
1. less memory
2. Fast
3. convenient


In [8]:
#1-dimensional array:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [9]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)
print(a.ndim,a1.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2


In [10]:
a1.shape
a.shape

(6,)

In [14]:
a3=np.array([],dtype="int32")
a3=np.append(a3,int(input()))
a3


45


array([45])

### Slicing

In [26]:
ar=np.arange(1,17)
ar=ar.reshape(4,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
print(ar[2])


[ 9 10 11 12]


In [28]:
print(ar[2:,:2])

[[ 9 10]
 [13 14]]


In [30]:
print(ar[2:])
print(ar[2:,:])

[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]


### iterating through array:

In [32]:
for row in ar:
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [33]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [34]:
ar2=np.arange(1,21).reshape(4,5)
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# indexing with boolaean array:

In [35]:


res=(ar2%2==0)
res

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [36]:
ar2[res]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [38]:
m1=np.arange(1,10).reshape(3,3)
m2=np.arange(11,20).reshape(3,3)
print(np.vstack((m1,m2)))          #vertical stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [39]:
print(np.hstack((m1,m2)))        #horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape


In [41]:
m3=np.arange(1,11).reshape(2,5)
m3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
print(m3.size)
print(m3.itemsize)
print(m3.dtype)
print(m3.ndim)
print(m3.shape)

10
4
int32
2
(2, 5)


### Functions:
1. zeros()
2. ones()
3. full()
4. eye()
5. arange()
6. reshape()
7. linspace()
8. ravel()

In [47]:
z=np.zeros((2,3),dtype="int32")
print(z,end='\n')
o=np.ones((3,3),dtype="int32")
print(o,end='\n')
f=np.full((2,2),"X")
print(f,end='\n')

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[['X' 'X']
 ['X' 'X']]


In [49]:
#eye()
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
# linear spacing elements
l=np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [55]:
# ravel
print(np.array(m3.flat))
print(m3.ravel())

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
### function:
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()

In [56]:
print(m3.max())
print(m3.min())

10
1


In [60]:
print(m3)
print(m3.sum(axis=1))
print(m3.sum(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[15 40]
[ 7  9 11 13 15]


In [61]:
np.sqrt(m3)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [62]:
np.mean(m3)

5.5

In [63]:
np.median(m3)

5.5

In [64]:
np.std(m3)

2.8722813232690143

### Mathematical Operations:

In [67]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(10,16).reshape(2,3)

b+a

array([[11, 13, 15],
       [17, 19, 21]])

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
b

array([[10, 11, 12],
       [13, 14, 15]])

In [68]:
b-a

array([[9, 9, 9],
       [9, 9, 9]])

In [69]:
b*a

array([[10, 22, 36],
       [52, 70, 90]])

In [72]:
b/a

array([[10.  ,  5.5 ,  4.  ],
       [ 3.25,  2.8 ,  2.5 ]])

In [73]:
b%a

array([[0, 1, 0],
       [1, 4, 3]], dtype=int32)

In [76]:
### dot()--> Matrix multiplication
### arr1 =m X n
### arr2 =n X l
print(m1.dot(m2))
m1*m2

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [80]:
### Applying user-defined functions on array:
f=lambda x:x/(x+1)
a=np.arange(1,20)
g=np.vectorize(f)
print(g(a))
f(a)

[0.5        0.66666667 0.75       0.8        0.83333333 0.85714286
 0.875      0.88888889 0.9        0.90909091 0.91666667 0.92307692
 0.92857143 0.93333333 0.9375     0.94117647 0.94444444 0.94736842
 0.95      ]


array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

Help on module random:

NAME
    random - Random variable generators.

DESCRIPTION
        integers
        --------
               uniform within range
    
        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation
    
        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)
               lognormal
               negative exponential
               gamma
               beta
               pareto
               Weibull
    
        distributions on the circle (angles 0 to 2pi)
        ---------------------------------------------
               circular uniform
               von Mises
    
    General notes on the underlying Mersenne Twister core generator:
    
    * The period is 2**19937-1.
    * It is one of the most extensively tested generators