In [12]:
from numpy import random as R
print(R.randint(30,100,size=4))
a=R.randint(30,100,size=(4,5))
print(a.ravel())


[51 66 88 85]
[99 87 36 72 55 93 83 66 55 32 33 79 48 66 77 62 74 56 71 46]
93


In [13]:
#single element will be selected:
print(R.choice(a.ravel()))


#generating array in given shape and elements from the give list:
R.choice([1,2,3,4,5],size=(4,4))

55


array([[1, 4, 4, 5],
       [3, 5, 1, 4],
       [2, 1, 2, 3],
       [2, 2, 4, 5]])

# Pandas
1. Data cleaning
2. Data manipulation
3. Tabular,unlabelled


In [8]:
### Creating a DataFrame
import pandas as pd
import numpy as np
di={'a':1,'b':2,'c':3,'d':4,'e':5}
dc={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":di,"second":dc}
df=pd.DataFrame(data,dtype=np.int32)
df

First  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [14]:
# simple dictionary as data frame
d1={"names":["rimac","tesla","koeniggsegg"],"model":["one","model Y",""]}
df2=pd.DataFrame(d1)
df2


names    model
0        rimac      one
1        tesla  model Y
2  koeniggsegg

In [38]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([2.4,23,25,24,345,235,34,235346,36346,9])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"c1":s1,"col2":s2,"c3":s3}
df3=pd.DataFrame(data)
df3

c1      col2 c3
0   1       2.4  a
1   2      23.0  b
2   3      25.0  c
3   4      24.0  d
4   5     345.0  e
5   6     235.0  f
6   7      34.0  g
7   8  235346.0  h
8   9   36346.0  i
9  10       9.0  j

In [18]:
df3['c1']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: c1, dtype: int64

In [19]:
df3['col2']

0         2.4
1        23.0
2        25.0
3        24.0
4       345.0
5       235.0
6        34.0
7    235346.0
8     36346.0
9         9.0
Name: col2, dtype: float64

In [22]:
df3[['c1','col2']]

c1      col2
0   1       2.4
1   2      23.0
2   3      25.0
3   4      24.0
4   5     345.0
5   6     235.0
6   7      34.0
7   8  235346.0
8   9   36346.0
9  10       9.0

### Selecting data from dataframe:


In [23]:
#loc     loc[row index,column]
# extracting single column
df3.loc[:,"col2"]

0         2.4
1        23.0
2        25.0
3        24.0
4       345.0
5       235.0
6        34.0
7    235346.0
8     36346.0
9         9.0
Name: col2, dtype: float64

In [24]:
# extracting multiple column values
df3.loc[0:5,['c1','col2']]

c1   col2
0   1    2.4
1   2   23.0
2   3   25.0
3   4   24.0
4   5  345.0
5   6  235.0

In [25]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: c1, dtype: int64

In [27]:
df3.iloc[0:4,0:2]

c1  col2
0   1   2.4
1   2  23.0
2   3  25.0
3   4  24.0

In [28]:
df3.shape

(10, 3)

In [29]:
df3.index

RangeIndex(start=0, stop=10, step=1)

In [30]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data frame DataFrame:
1. head()
2. tail()
3. sample()

In [31]:
df3.head()

c1   col2 c3
0   1    2.4  a
1   2   23.0  b
2   3   25.0  c
3   4   24.0  d
4   5  345.0  e

In [32]:
df3.tail()

c1      col2 c3
5   6     235.0  f
6   7      34.0  g
7   8  235346.0  h
8   9   36346.0  i
9  10       9.0  j

In [33]:
df3.sample(3)

c1      col2 c3
7   8  235346.0  h
3   4      24.0  d
0   1       2.4  a

In [34]:
df3.describe()

c1           col2
count  10.00000      10.000000
mean    5.50000   27238.940000
std     3.02765   74004.016506
min     1.00000       2.400000
25%     3.25000      23.250000
50%     5.50000      29.500000
75%     7.75000     317.500000
max    10.00000  235346.000000

In [39]:
df3=df3.rename(columns={"c1":"A","col2":"B","c3":"C"})
df3

A         B  C
0   1       2.4  a
1   2      23.0  b
2   3      25.0  c
3   4      24.0  d
4   5     345.0  e
5   6     235.0  f
6   7      34.0  g
7   8  235346.0  h
8   9   36346.0  i
9  10       9.0  j