In [4]:
import numpy as np
a=np.arange(1,10)
print(a,type(a))
b=a[::-1]
print(b,type(b))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[9 8 7 6 5 4 3 2 1] <class 'numpy.ndarray'>


In [7]:
n=int(input("Enter size:"))
pat=np.ones((n,n),dtype="int32")
pat[1:-1,1:-1]=0
pat

Enter size:8


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])