# Question 1:
[Reversing an Array] 
Write a NumPy program to reverse an array (first element becomes last). 
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [4]:
import numpy as np
a=np.arange(1,10)
print(a,type(a))
b=a[::-1]
print(b,type(b))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[9 8 7 6 5 4 3 2 1] <class 'numpy.ndarray'>


# Question 2:
[Make Border 1] 
Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
Expected output:
[[ 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
……………..
 [1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]


In [7]:
n=int(input("Enter size:"))
pat=np.ones((n,n),dtype="int32")
pat[1:-1,1:-1]=0
pat

Enter size:8


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

# Question 3:
    [Membership Test] 
    Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
    Expected Output:
    Array1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [33]:
import numpy as np
r=np.array([0,10,20,40,60])
s=np.array([0,40])
res=np.isin(r,s)
print(res)

[ True False False  True False]


# Question 4:
    [Set Difference] 
    Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
    Expected Output:
    Array1: [ 0 10 20 40 60 80]
    Array2: [10, 30, 40, 50, 70, 90]
    Set difference between two arrays:
    [ 0 20 60 80]


In [36]:
l1=[int(i) for i in input().split()]
l2=[int(i) for i in input().split()]
r=np.array(l1)
s=np.array(l2)
d=np.setdiff1d(r,s)
d

10 30 40 50 70 90
0 10 20 40 60 80


array([30, 50, 70, 90])

# Question 5:
    [Formation of Diagonal Matrix] 
    Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
    Expected Output:
    [[4 0 0 0]
    [0 5 0 0]
    [0 0 6 0]
    [0 0 0 8]]


In [38]:
l1=[int(i) for i in input().split()]
r=np.array(l1)
mat=np.diag(r)
mat

4 5 6 8


array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])